version: "3"

services:
  redis:
    image: redis:latest
  api:
    image: "cache-api"
    ports:
      - "4000:4000"
    depends_on:
      - "redis"
    environment:
      NODE_ENV: "production"
      API_HOST: "0.0.0.0"
      API_PORT: 4000
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
